### ISSUE TITLE
Colour coding of Transactions

### ISSUE THREAD

**Issue by FlyingFordAnglia** [Stochastic13/homeFinance#2]
**The Bug**
_Transactiono colorus_

**Steps to reproduce the behavior:**

1. Go to 'Numeric tab'
2. Click on 'Analyze!'
3. Check out the transactions list.
4. Some of the transactions are marked in green, some in black and some in red, with no association with net change (Plus, No change and Minus).

**Expected behavior**
I wouldn't have expected any colours in the first place.

**Screenshots**
![bug report coins](https://user-images.githubusercontent.com/47173623/63706881-20837080-c84e-11e9-92a0-829e3039434b.png)

The transactions are fake!! Just saying.

**Version control**
 - Version of app: 0.3
 - Python 3.6

**Comment by Stochastic13** [comment]
Thank you for reporting. The issue was due to `tkinter` not allowing white spaces in the `tag` name in the `Text` widget. Fixed in the latest commit.
